version: '3.1'
services:
  application:
    image: "node:16"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV:development
    volumes:
      - ./app:/home/node/app
    ports:
      - 3000:8000
    command: "npm run serve"
  
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME:root
      - MONGO_INITDB_ROOt_PASSWORD:productservice
      - MONGO_INITDB_DATABASE:Product

  mongo-express:
    image: mongo-express
    ports:
      - 3001:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME:root
      - ME_CONFIG_MONGODB_ADMINPASSWORD:productservice
      - ME_CONFIG_MONGODB_URL:mongo://root:productservice@mongo:27017/